name: PostgreSQL Service 
on: push

jobs:
  container-job:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm ci

      - name: Install migrate database
        run: npm run migrate up
        env:
          POSTGRES_HOST: ${{ secrets.PGHOST_TEST }}
          POSTGRES_PORT: ${{ secrets.PGPORT_TEST }}
