name: PostgreSQL Service 
on: 
  pull_request:
    branches:
      - master

jobs:
  postgres:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    services:
      postgres:
        image: postgres
        env:
          PGPASSWORD: ${{ secrets.PGPASSWORD_TEST }}
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Install migrate database
        run: npm run migrate up
        env:
          PGHOST: ${{ secrets.PGHOST_TEST }}
          PGPORT: ${{ secrets.PGPORT_TEST }}
